package AddressBook::Web::Model::DBIC;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'AddressBook::Web::Schema',
    
    connect_info => {
        dsn => 'dbi:mysql:address_book',
        user => 'test_user',
        password => 'test_password',
    }
);

=head1 NAME

AddressBook::Web::Model::DBIC - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<AddressBook::Web>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<AddressBook::Web::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.65

=head1 AUTHOR

mshr

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
